name: cure_buddy
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  smooth_page_indicator: ^1.1.0
  http: 1.3.0
  jwt_decoder: ^2.0.1
  google_fonts: ^6.1.0
  shared_preferences: ^2.5.3
  file_picker: ^10.1.2
  intl: ^0.20.2
  flutter_secure_storage: ^9.0.0
  fluttertoast: ^8.2.2
  url_launcher: ^6.2.5
  fl_chart: ^0.63.0
  flutter_launcher_icons: ^0.9.2
  google_maps_flutter: ^2.5.0
  permission_handler: ^11.3.0
  logger: ^2.2.0





dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/intro1.gif
    - assets/intro2.gif
    - assets/intro3.gif
    - assets/doctor_login.gif
    - assets/doctor_register.gif
    - assets/patient_register.gif
    - assets/doctor_card_image.png
    - assets/patient_avatar.png





